# Site settings
title: Felix Blog
SEOTitle: 马子超的博客 | Felix Blog
header-img: img/home-bg.jpg
email: 1374147274@qq.com
description: "个人博客"
keyword: "Blog, Web, 互联网, 博客"
url: "https://felix-ma.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     5339871440
zhihu_username:     ma-zi-chao-30-94
github_username:    felix-ma
twitter_username:  mzc_continue
#facebook_username:  felix



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: blog-qy6sb8lbmh

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-117503250-1'            # Format: UA-xxxxxx-xx
ga_domain: felix-ma.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "任何你写的代码，超过6个月不去看它，当你再看时，都像是别人写的。"
sidebar-avatar: /img/avatar-felix-ma.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "poslua",
        href: "http://ms2008.github.io"
    },{
        title: "Gogs",
        href: "http://123.206.29.95/"
    },{
        title: "Flarum",
        href: "http://139.199.37.48/"
    }
]
